export const HIDE_MODEL = 'model/HIDE_MODEL';
export const SHOW_MODEL = 'model/SHOW_MODEL';

export const LOAD_MODEL_CONFIG = 'model/LOAD_MODEL_CONFIG';
export const LOAD_MODEL_CONFIG_SUCCESS = 'model/LOAD_MODEL_CONFIG_SUCCESS';
export const LOAD_MODEL_CONFIG_FAIL = 'model/LOAD_MODEL_CONFIG_FAIL';

export const CHECK_OPEN_EDIT_FROM_DIALOG = 'model/CHECK_OPEN_EDIT_FROM_DIALOG';


